name: obesity-model-env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy~=1.23.5
  - pandas~=1.5.3
  - scikit-learn~=1.2.2
  - joblib~=1.2.0
  - pip
  - pip:
    - azureml-defaults~=1.51.0
    - inference-schema